version: '3'
services:
    web:
        build: .
        ports:
            - 4000:4000
        volumes:
            - ./logs:/logs
        environment:
            - NODE_ENV=development
            - HOST=0.0.0.0
            - PORT=4000
        restart: always